### ISSUE TITLE
Broken CMake package file generated

### ISSUE THREAD

**Issue by alexdewar** [ros-noetic-arch/ros-noetic-urdf#2] opened 2021-10-22 10:27 UTC
I think I've root-caused this issue: https://github.com/ros-noetic-arch/ros-noetic-diff-drive-controller/issues/2

The problem is in ``/opt/ros/noetic/share/urdf/cmake/urdfConfig.cmake``:
```cmake
set(libraries "urdf;$<$<NOT:$<CONFIG:Debug>>:/usr/lib/liburdfdom_sensor.so>;$<$<CONFIG:Debug>:/usr/lib/liburdfdom_sensor.so>;$<$<NOT:$<CONFIG:Debug>>:/usr/lib/liburdfdom_model_state.so>;$<$<CONFIG:Debug>:/usr/lib/liburdfdom_model_state.so>;$<$<NOT:$<CONFIG:Debug>>:/usr/lib/liburdfdom_model.so>;$<$<CONFIG:Debug>:/usr/lib/liburdfdom_model.so>;$<$<NOT:$<CONFIG:Debug>>:/usr/lib/liburdfdom_world.so>;$<$<CONFIG:Debug>:/usr/lib/liburdfdom_world.so>;/usr/lib/libconsole_bridge.so.1.0;/usr/lib/libboost_thread.so.1.76.0;/usr/lib/libtinyxml.so;/usr/lib/libtinyxml2.so")
```

All the angle brackets don't *look* like valid CMake to me and in any case the debug/non-debug libraries appear to be the same so it's redundant anyway.

This causes an error later on in the build process for packages using this CMake package:
```cmake
      # as a fall back for non-catkin libraries try to search globally
      find_library(lib ${library})
      if(NOT lib)
        message(FATAL_ERROR "Project '${PROJECT_NAME}' tried to find library '${library}'.  The library is neither a target nor built/installed properly.  Did you compile project 'urdf'?  Did you find_package() it before the subdirectory containing its code is included?")
      endif()
```

I fixed things by replacing the offending line above thus:
```cmake
set(libraries "urdf;/usr/lib/liburdfdom_sensor.so;/usr/lib/liburdfdom_model_state.so;/usr/lib/liburdfdom_model.so;/usr/lib/liburdfdom_world.so;/usr/lib/libconsole_bridge.so.1.0;/usr/lib/libboost_thread.so.1.76.0;/usr/lib/libtinyxml.so;/usr/lib/libtinyxml2.so")
```

I'm not sure how we should proceed to fix things permanently though?

**Comment by alexdewar** [comment] 2021-10-23 10:52
Unfortunately your last push to the AUR hasn't fixed things. There are still trailing ``>``s in the CMake file so I'm now getting build errors like so:
```
make[2]: *** No rule to make target '/usr/lib/liburdfdom_sensor.so>', needed by 'devel/lib/diff_drive_controller/skidsteerbot'.  Stop.
```

**Comment by acxz** [comment] 2022-01-31 16:06
I did a bit more digging and found the root cause.

[Here](https://github.com/ros/urdfdom/commit/c83e7715eaa124369389ef80a1814fca5b9e53b8) is the commit that fixes it. It has been released for `urdfdom=3.0.1`. Just waiting on @nim65s to update the package and we can close this issue.

**Comment by nim65s** [comment] 2022-01-31 23:38
done, thanks :)

**Comment by acxz** [comment] 2022-01-31 23:48
thanks for the quick response as always, @nim65s!

**Closed as completed by acxz** 2022-01-31 23:48 UTC
